ALTER TABLE stock_ins
  ADD COLUMN IF NOT EXISTS unit_price   NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS performed_by VARCHAR(255)   NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS location     VARCHAR(255)   NOT NULL DEFAULT '';

ALTER TABLE stock_outs
  ADD COLUMN IF NOT EXISTS unit_price   NUMERIC(15,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS performed_by VARCHAR(255)   NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS location     VARCHAR(255)   NOT NULL DEFAULT '';
